CREATE TABLE Clients(
ID INT PRIMARY KEY IDENTITY(1,1),
FirstName NVARCHAR(50) NOT NULL,
LastName NVARCHAR(50) NOT NULL,
)

CREATE TABLE AccountTypes(
ID INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE Accounts(
ID INT PRIMARY KEY IDENTITY(1,1),
AccountTypeId INT FOREIGN KEY REFERENCES AccountTypes(Id),
Balance DECIMAL(15,2) NOT NULL DEFAULT(0),
ClientId INT FOREIGN KEY REFERENCES Clients(ID)
)